name: CI on Pull Request to main branch

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DWNLD_PKGS: 'yaml-cpp yaml-cpp-devel sailfish-svg2png'
      DWNLD_REPO: 'https://repo.merproject.org/obs/sailfishos:/chum'
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    #- name: Prepare
    #  run: 

    # Caching Docker images is not ready yet, see 
    # https://github.com/storeman-developers/harbour-storeman-installer/blob/devel/cache-docker-images_github-ci.md
    #- name: Cache Docker images of the Sailfish-SDK
    #  id: cache-sdk
    #  uses: actions/cache@v3
    #  with:
    #    path: $GITHUB_WORKSPACE/…
    #    key: cache

    - name: Build ${{ env.ARCH }} on ${{ env.RELEASE }}
      env:
        ARCH: armv7hl
        #RELEASE: 3.1.0.12
        RELEASE: 3.4.0.24
        #RELEASE: 4.0.1.45
      # mb2 wants bash: https://github.com/sailfishos/sdk-setup/blob/master/sdk-setup/src/mb2#L1
      run: |
        mkdir -p output/$RELEASE/$ARCH
        export 
        docker run --rm --privileged -v $PWD:/share coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -xc '
            mkdir -p rpmbuild/SOURCES ;
            printf "%s" "${{ secrets.TOKEN_GITHUB }}" > rpmbuild/SOURCES/token-github.txt ;
            printf "%s" "${{ secrets.TOKEN_GITLAB }}" > rpmbuild/SOURCES/token-gitlab.txt ;
            mkdir -p build/rpm ;
            cp rpmbuild/SOURCES/token-git??b.txt build/rpm/ ;
            mkdir -p build/RPMS ;
            cd build/RPMS ;
            Filter="[A-Za-z][+.0-9A-Z_a-z-]*" ;  # Filter="[A-Za-z][+0-9A-Z_a-z-]*-[0-9][+.0-9A-Z_a-z]*-[+.0-9A-Z_a-z]+" ;
            List="$(curl -sf "$3/${1}_$2/{${2},noarch}/" | egrep -o "${Filter}\.${2}\.rpm|${Filter}\.noarch\.rpm" | uniq)" ;
            for i in $4 ; 
            do curl -sfO "$3/$(echo "$List" | grep "^$i-[0-9][+.0-9A-Z_a-z-]*")" ;
            done ;
            cp * ../rpm/
            cd .. ;
            cp -r /share/. ./ ;
            foo="$(ls -l RPMS)" ;
            bar="$(ls -la .)" ;
            car="$(ls -la ..)" ;
            # mb2 build-shell --maintain zypper ar sailfishos-chum "$3/%(release)_%(arch)/" ;
            mb2 -t SailfishOS-$1-$2 --output-dir ./RPMS build -d ;
            sudo cp -r RPMS/*.rpm /share/output/$1/$2/' bash_mb2 "$RELEASE" "$ARCH" "$DWNLD_REPO" "$DWNLD_PKGS"

    - name: Upload build results
      uses: actions/upload-artifact@v3
      with:
        name: RPM-build-results
        path: output/

    - name: Create release
      if: contains(github.ref, 'release')
      run: |
        set -x
        assets=""
        for asset in output/*/*/*.rpm; do
          assets="$assets -a $asset"
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create"$assets" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
